import streamlit as st
import requests
from io import BytesIO
from PIL import Image
import random

# --- CONFIGURATION ---
# PASTE YOUR KEY HERE
API_KEY = "sk_Z0oEnm05szbphnbZ9ClRCukKV2HyDMH5"

st.set_page_config(page_title="Alpha AI Elite", page_icon="🤖", layout="wide")

# --- UI STYLING ---
st.markdown("""
    <style>
    .stApp { background-color: #050505; color: white; }
    .stTextInput > div > div > input { background-color: #111; color: #00ffcc; border: 1px solid #333; }
    .stButton > button { 
        width: 100%; 
        background: linear-gradient(90deg, #00ffcc, #0088ff); 
        color: black; font-weight: bold; border: none; padding: 12px;
    }
    footer {visibility: hidden;}
    </style>
    """, unsafe_allow_html=True)

# --- HEADER ---
st.title("🤖 Alpha AI Elite: Image Engine")
st.write(f"Created by **Hasith Heshan** | Model: **Flux Schnell**")
st.write("---")

# --- INPUTS ---
col1, col2 = st.columns([2, 1])

with col1:
    prompt = st.text_area("What should Alpha AI visualize?", placeholder="Example: A futuristic battle-mech in the rain, 8k, highly detailed...")

with col2:
    style = st.selectbox("Select Style", ["Cinematic", "Realistic", "Anime", "Cyberpunk", "Digital Art"])
    aspect = st.selectbox("Aspect Ratio", ["1:1 (Square)", "16:9 (Widescreen)", "9:16 (Portrait)"])

# --- GENERATION LOGIC ---
if st.button("GENERATE MASTERPIECE 🚀"):
    if prompt:
        with st.spinner("Alpha AI is authenticating and generating..."):
            # Prepare dimensions
            width, height = 1024, 1024
            if aspect == "16:9": height = 576
            elif aspect == "9:16": width = 576
            
            seed = random.randint(1, 999999)
            full_prompt = f"{prompt}, {style} style, high resolution, masterpiece"
            
            # API URL and Headers
            # We use the 'flux' model you saw in your screenshot
            url = f"https://image.pollinations.ai/prompt/{full_prompt}?width={width}&height={height}&seed={seed}&model=flux&nologo=true"
            
            headers = {
                "Authorization": f"Bearer {API_KEY}"
            }
            
            try:
                response = requests.get(url, headers=headers, timeout=60)
                
                if response.status_code == 200:
                    img = Image.open(BytesIO(response.content))
                    st.image(img, caption="Generated by Alpha AI", use_container_width=True)
                    
                    # Download Button
                    buf = BytesIO()
                    img.save(buf, format="PNG")
                    st.download_button(
                        label="Download Image 📥",
                        data=buf.getvalue(),
                        file_name="alpha_ai_generated.png",
                        mime="image/png"
                    )
                elif response.status_code == 401:
                    st.error("API Key Error: Please check if your key is copied correctly.")
                else:
                    st.error(f"Error: {response.status_code}. Server might be busy.")
                    
            except Exception as e:
                st.error(f"Connection failed: {e}")
    else:
        st.warning("Please enter a description first!")

st.markdown("---")
st.caption("Alpha AI Project | Bandarawela Central College")
